### ISSUE TITLE
Turn StatusCounts into [600]*int

### ISSUE THREAD

**Issue by erikdubbelboer** [forestgagnon/ravager#1]
Using `StatusCounts [600]*int` will use less memory and will be much faster (no hashing etc).

Just make sure to write this
https://github.com/forestgagnon/ravager/blob/c3b2bc739582b17a5abee433617e27d9f7dd56ae/main.go#L128
like:
```go
if statusCode := resp.StatusCode(); statusCode < len(stats.StatusCounts) {
  atomic.AddUint64(stats.StatusCounts[statusCode], 1)
}
```

Sorry I don't have time to make a pull request right now.

**Comment by forestgagnon** [comment]
thanks for the tip!
